mixed-port: 7890
allow-lan: true
bind-address: '*'
mode: rule
log-level: debug
ipv6: false
external-controller: 127.0.0.1:9090
dns:
  enable: true
  ipv6: false
  listen: ':1053'
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  fake-ip-filter:
    - '*.lan'
    - '*.local'
    - 'stun.*.*'
    - 'stun.*.*.*'
    - '+.stun.*.*'
    - '*.apple.com'
    - '*.localhost'
    - '+.stun.*.*.*'
    - '+.stun.*.*.*.*'
    - ntp.ntsc.ac.cn
    - '*.msftncsi.com'
    - lens.l.google.com
    - 'localhost.*.qq.com'
    - '*.mcdn.bilivideo.cn'
    - '*.msftconnecttest.com'
  default-nameserver:
    - 223.5.5.5
    - 223.6.6.6 
    - 114.114.114.114
  nameserver: 
    - https://dns.alidns.com/dns-query
    - https://doh.pub/dns-query
